"use client";

import React, { useEffect, useState } from "react";
import NavComp from "../Component/Navbar/nav";
import { getData, getImageUrl } from "./apicall/apicallservice";
import { Menuinterface } from "../Interface/menuinterface";

export const metadata = {
  title: "Menu",
  description: "Generated by create next app",
};

const page = () => {
  const [matchaMenu, SetmacthaMenu] = useState<Menuinterface[]>([]);
  const [selectedCategory, setSelectedCategory] = useState("All");
  
  useEffect(() => {
    const fetchMenuData = async () => {
      try {
        const data = await getData();
        console.log("Fetched data:", data);
        SetmacthaMenu(data); // Set the fetched data to state
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };

    fetchMenuData();
  }, []);
  
  const categories = ["All Categories", ...Array.from(new Set(matchaMenu.map(item => item.category)))];

  const handleCategoryChange = (e:any) => {
    setSelectedCategory(e.target.value);
  };
  
  return (
    <>
      <NavComp loggedInUser={null}></NavComp>
      <div>
        <div className="p-10 px-4 text-center text-lg flex justify-between items-center">
          <h3 className="text-center">Our Best Product</h3>
          <select
            className="w-32 rounded-lg bg-blue-300 bg-opacity-50 font-normal text-sm text-center"
            value={selectedCategory}
            onChange={handleCategoryChange}
          >
            {categories.map((category, index) => (
              <option key={index} value={category}>
                {category}
              </option>
            ))}
          </select>
        </div>

        <div className="w-full flex items-center justify-center px-4 mb-2">
          <div>
            {categories.map((category) => (
              <div key={category}>
                <h2 className="text-2xl font-semibold mb-2 text-center">{category}</h2>
                <div className="grid grid-cols-2 gap-4">
                  {matchaMenu
                    .filter((menuItem) => selectedCategory === "All" || menuItem.category === category)
                    .map((menuItem) => (
                      <div className="px-3 mb-5" key={menuItem._id}>
                        <div className="max-w-md p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                          <figure>
                            <img src={getImageUrl(menuItem.imagePath)} alt="Matcha" className="mx-auto max-w-full" />
                          </figure>
                          <a href="#">
                            <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                              {menuItem.title}
                            </h5>
                          </a>
                          <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">
                            {menuItem.description}
                          </p>
                          <a
                            href="#"
                            className="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                          >
                            Rp. {menuItem.harga}
                          </a>
                        </div>
                      </div>
                    ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  );
};

export default page;
